# Change these first
owner: muenchnerfurs # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: muenchner-furs.de
    url: https://muenchner-furs.de
  - name: Eventanmeldung (Pretix)
    url: https://reg.muenchner-furs.de
  - name: furvaria.de
    url: https://furvaria.de
  - name: donaufurs.de
    url: https://donaufurs.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.muenchner-furs.de
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoring
  introTitle: "**Systemstatus** Münchner Furs e. V."
  introMessage: Status über die Verfügbarkeit und Erreichbarkeit der IT.
  navbar:
    - title: Status
      href: /
    - title: Telegram
      href: https://t.me/MuenchnerFurs
    - title: Bluesky
      href: https://bsky.app/profile/muenchner-furs.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
